name: Build Loop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Build Loop
        run: xcodebuild -workspace LoopWorkspace.xcworkspace -scheme Loop -destination generic/platform=iOS
        env:
          DEVELOPMENT_TEAM: ${{ secrets.TEAMID }}
