name: Build Loop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Install Xcode Tools
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.2.app
          sudo xcodebuild -license accept

      - name: Build Loop
        uses: LoopKit/LoopWorkspace/.github/actions/browser-build@main
        with:
          team-id: ${{ secrets.TEAMID }}
