name: Browser Build Loop
on:
  workflow_dispatch:  # Manueller Trigger
  schedule:
    - cron: "0 9 * * 3"  # Mittwochs um 09:00 UTC
    - cron: "0 7 1 * *"  # Am 1. jedes Monats um 07:00 UTC

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build Loop
        uses: LoopKit/LoopWorkspace/.github/workflows/build-loop@main
        with:
          team-id: ${{ secrets.TEAMID }}  # Einzige benötigte Angabe
